
@host=http://113.30.148.96

//=====AUTHETICATION========
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "email":"encargadoprimero@almacen.es",
    "contrasena": "password123"
}

###
// Registra nuevo jefe de equipo
POST {{host}}/api/auth/register
Content-Type: application/json

{
    "nombre": "cyril",
    "apellido":"operario",
    "email":"operario4@almacen.es",
    "contrasena": "password123",
    "ciudad": "Barcelona",
    "codigo_postal":"08005",
    "roles_id":2
}
###