@host = http://113.30.148.96:3000



//=====CAMIONES========
###
// Crear nuevo camion
POST {{host}}/api/camiones/nuevo
Content-Type: application/json
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MjYsInJvbGVzX2lkIjoyLCJleHAiOjE2ODk1MzQ3OTAsImlhdCI6MTY4Njk0Mjc5MH0.IBDqWTdTYe7LtTe10CpO-97yIsVRXUg5YKYdGqNrwZg

{
    "matricula_camion":"ABC1234",
    "capacidad_maxima":"40",
    "estado":"Habilitado"
}

###
//Recupera todos los camiones
GET {{host}}/api/camiones
authorization : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MjYsInJvbGVzX2lkIjoyLCJleHAiOjE2ODk1MzQ3OTAsImlhdCI6MTY4Njk0Mjc5MH0.IBDqWTdTYe7LtTe10CpO-97yIsVRXUg5YKYdGqNrwZg

###
// para ver los detalles de un camion
GET {{host}}/api/camiones/1

###
// para actualizar los detalles de un camion
PUT {{host}}/api/camiones/1
Content-Type: application/json 

{
    "estado":"Inactivo"
}


###
// para borrar un camion
DELETE {{host}}/api/camiones/1