@host = http://localhost:3000



//=====MATERIALES========
###
// Crear nuevo material
POST {{host}}/api/materiales/nuevo
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MzQsInJvbGVzX2lkIjo0LCJleHAiOjE2ODk1MzA1NzIsImlhdCI6MTY4NjkzODU3Mn0.g9iSI5nuJuaPBmHGt2r4kZdLRgsx8NCuGjOhn285BRE

{
    "estado":"Nuevo",
    "peso":6.28,
    "nombre":"Fresones",
    "descripcion_material":"fresones de verano",
    "categorias_materiales_id":1
}

###
//Recupera todos los materiales
GET {{host}}/api/materiales
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MzYsInJvbGVzX2lkIjozLCJleHAiOjE2ODk3MTI4NzQsImlhdCI6MTY4NzEyMDg3NH0.X7G2ylNghRMs22oa9Yf3r3UDSYS7bYKvLahX4XapFHE
###
// para ver los detalles de un material
GET {{host}}/api/materiales/6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MjcsInJvbGVzX2lkIjozLCJleHAiOjE2ODk0MzI5MjAsImlhdCI6MTY4Njg0MDkyMH0.qxmqz2O31iHQjCq6m2lWC54EmfEyNngPz-sK5Pwoy-A

###
// para actualizar los detalles de un metarial
PUT {{host}}/api/materiales/6
Content-Type: application/json 
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MjYsInJvbGVzX2lkIjoyLCJleHAiOjE2ODk1Mzg0NjIsImlhdCI6MTY4Njk0NjQ2Mn0.hZSdW-M7svEtMSh5zZSyKcMlPphq3kfaekHvDNHtH8k


{
    "descripcion_material":"Fresones de verano "
}


###
// para borrar un material
DELETE {{host}}/api/materiales/3
authorization : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MjcsInJvbGVzX2lkIjozLCJleHAiOjE2ODk0MzI5MjAsImlhdCI6MTY4Njg0MDkyMH0.qxmqz2O31iHQjCq6m2lWC54EmfEyNngPz-sK5Pwoy-A
