@host = http://localhost:3000



//=====MATERIALES========
###
// Crear nuevo material
POST {{host}}/api/materiales/nuevo
Content-Type: application/json
authorization : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MjcsInJvbGVzX2lkIjozLCJleHAiOjE2ODk0MzI5MjAsImlhdCI6MTY4Njg0MDkyMH0.qxmqz2O31iHQjCq6m2lWC54EmfEyNngPz-sK5Pwoy-A

{
    "estado":"Nuevo",
    "peso":2.38,
    "nombre":"Fresas",
    "descripcion_material":"fresas de verano",
    "categorias_materiales_id":1
}

###
//Recupera todos los materiales
GET {{host}}/api/materiales
authorization : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MjcsInJvbGVzX2lkIjozLCJleHAiOjE2ODk0MzI5MjAsImlhdCI6MTY4Njg0MDkyMH0.qxmqz2O31iHQjCq6m2lWC54EmfEyNngPz-sK5Pwoy-A


###
// para ver los detalles de un material
GET {{host}}/api/materiales/4

###
// para actualizar los detalles de un metarial
PUT {{host}}/api/materiales/4
Content-Type: application/json 

{
    "descripcion_material":"Fresón "
}


###
// para borrar un material
DELETE {{host}}/api/materiales/3
