@host = http://localhost:3000



//=====PEDIDOS========
###
// Crear nuevo pedido
POST {{host}}/api/pedidos/nuevo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MzQsInJvbGVzX2lkIjo0LCJleHAiOjE2ODk1NTMyMjIsImlhdCI6MTY4Njk2MTIyMn0.u5RyhXWfu9Ps6oFcpHC2N4922vWssNyi_DRAEDg3xxU

{
  "fecha_salida": "2023-06-19T17:01",
  "fecha_llegada": "2023-06-22T17:01",
  "estado_pedido": "En revisión",
  "medida": "1",
  "fecha_creacion": "2023-06-18 05:01:13",
  "usuarios_id_creador": "34",
  "usuarios_id_revisador": 26,
  "almacenes_id_origen": "9",
  "almacenes_id_destino": "3",
  "camiones_id": "14",
  "usuarios_id_aprobador": 26,
  "observaciones": "",
  "stocks": [
    {
      "posicion": 1,
      "stocks_id": "6",
      "unidades": 2,
      "materiales_id": 4
    }
  ]
}
###
//Recupera todos los pedidos
GET {{host}}/api/pedidos
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MzQsInJvbGVzX2lkIjo0LCJleHAiOjE2ODk1NTMyMjIsImlhdCI6MTY4Njk2MTIyMn0.u5RyhXWfu9Ps6oFcpHC2N4922vWssNyi_DRAEDg3xxU


###
// para ver los detalles de un pedido
GET {{host}}/api/pedidos/63
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MzQsInJvbGVzX2lkIjo0LCJleHAiOjE2ODk1NTMyMjIsImlhdCI6MTY4Njk2MTIyMn0.u5RyhXWfu9Ps6oFcpHC2N4922vWssNyi_DRAEDg3xxU

###
// para actualizar los detalles de un pedido
PUT {{host}}/api/pedidos/63
Content-Type: application/json 
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MzQsInJvbGVzX2lkIjo0LCJleHAiOjE2ODk1NTMyMjIsImlhdCI6MTY4Njk2MTIyMn0.u5RyhXWfu9Ps6oFcpHC2N4922vWssNyi_DRAEDg3xxU

{
    "medida":3.14,
    "stocks":[{"stocks_id":3, "unidades":460,"posicion":1},{"stocks_id":4,"unidades":180,"posicion":2}]
}


###
// para borrar un pedido
DELETE {{host}}/api/pedidos/57
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MjYsInJvbGVzX2lkIjoyLCJleHAiOjE2ODk1Mzg0NjIsImlhdCI6MTY4Njk0NjQ2Mn0.hZSdW-M7svEtMSh5zZSyKcMlPphq3kfaekHvDNHtH8k
