@host=http://almazenunir.es


//=====PEDIDOS========
###
// Crear nuevo pedido
POST {{host}}/api/pedidos/nuevo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MzgsInJvbGVzX2lkIjo0LCJleHAiOjE2ODk3NDc4MzQsImlhdCI6MTY4NzE1NTgzNH0.nNDqyeO0hqABhXwILwANoT6Y0wX2Q2_-IArPRUe6cXk

{"fecha_salida":"2023-06-20 15:32:01",
"fecha_llegada":"2023-06-19 15:32:02",
"medida":2.3,
"fecha_creacion":"2023-06-18 15:32:00",
"usuarios_id_creador":38,
"usuarios_id_revisador":41,
"almacenes_id_origen":9,
"almacenes_id_destino":3,
"camiones_id":14,
"usuarios_id_aprobador":43,
"stocks":[{"stocks_id":6,"unidades":30,"posicion":1},{"stocks_id":7,"unidades":60,"posicion":2}]}

###
//Recupera todos los pedidos
GET {{host}}/api/pedidos
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MzAsInJvbGVzX2lkIjozLCJleHAiOjE2OTAzNzgzMjEsImlhdCI6MTY4Nzc4NjMyMX0.AsomGl267ng0hqS1Rnd4qPahCJuoPIhUvQeVXPRtC1E

###
// para ver los detalles de un pedido
GET {{host}}/api/pedidos/95
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6NDEsInJvbGVzX2lkIjozLCJleHAiOjE2ODk3NTQ0OTIsImlhdCI6MTY4NzE2MjQ5Mn0.wVWNrRWDZ8QTPUfqTGuu_8zMtqRqL20zEQGhOtcIZPM

###
// para actualizar los detalles de un pedido
PUT {{host}}/api/pedidos/102
Content-Type: application/json 
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MzYsInJvbGVzX2lkIjozLCJleHAiOjE2ODk3ODY5MzAsImlhdCI6MTY4NzE5NDkzMH0.xIxn-FcS6YOCa9el5LvB6ryOTJJUeNyHLiXzKG8r-1U

{
    "estado_pedido":"Aprobado"
}


###
// para borrar un pedido
DELETE {{host}}/api/pedidos/90
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MjYsInJvbGVzX2lkIjoyLCJleHAiOjE2ODk1Mzg0NjIsImlhdCI6MTY4Njk0NjQ2Mn0.hZSdW-M7svEtMSh5zZSyKcMlPphq3kfaekHvDNHtH8k
