@host = http://localhost:3000



//=====PEDIDOS========
###
// Crear nuevo pedido
POST {{host}}/api/pedidos/nuevo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MzQsInJvbGVzX2lkIjo0LCJleHAiOjE2ODk1NTMyMjIsImlhdCI6MTY4Njk2MTIyMn0.u5RyhXWfu9Ps6oFcpHC2N4922vWssNyi_DRAEDg3xxU

{
    "fecha_salida":"{{$datetime 'YYYY-MM-DD HH:mm:ss' +2 d}}",
    "fecha_llegada":"{{$datetime 'YYYY-MM-DD HH:mm:ss' +2 d}}",
    "estado_pedido":"Entregado",
    "medida":2.3,
    "fecha_creacion":"{{$datetime 'YYYY-MM-DD HH:mm:ss'}}",
    "usuarios_id_creador":34,
    "usuarios_id_revisador":27,
    "almacenes_id_origen":2,
    "almacenes_id_destion":3,
    "camiones_id":2,
    "usuario_id_aprobador":28,
    "stocks":[{"materiales_id":3,"stocks_id":7,"unidades":30,"posicion":1},
            {"materiales_id":4,"unidades":60,"stocks_id":7,"posicion":2}]
}

###
//Recupera todos los pedidos
GET {{host}}/api/pedidos
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MjcsInJvbGVzX2lkIjozLCJleHAiOjE2ODk0NDE5MjAsImlhdCI6MTY4Njg0OTkyMH0.i-_lfyysvqlVasbhP05-LvPavolSmHLYZgYn98jGg5k


###
// para ver los detalles de un pedido
GET {{host}}/api/pedidos/37

###
// para actualizar los detalles de un pedido
PUT {{host}}/api/pedidos/11
Content-Type: application/json 
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MjcsInJvbGVzX2lkIjozLCJleHAiOjE2ODk0NDE5MjAsImlhdCI6MTY4Njg0OTkyMH0.i-_lfyysvqlVasbhP05-LvPavolSmHLYZgYn98jGg5k

{
    "medida":3.14,
    "stocks":{"3":{"unidades":46,"posicion":1},"4": {"unidades":18,"posicion":2}}
}


###
// para borrar un pedido
DELETE {{host}}/api/pedidos/2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MjYsInJvbGVzX2lkIjoyLCJleHAiOjE2ODk1Mzg0NjIsImlhdCI6MTY4Njk0NjQ2Mn0.hZSdW-M7svEtMSh5zZSyKcMlPphq3kfaekHvDNHtH8k
