
@host=http://localhost:3000


//=====USUARIOS========
###
// Crear nuevo usuario
POST {{host}}/api/usuarios/nuevo
Content-Type: application/json

{
    "nombre": "cyril",
    "apellido":"operario",
    "email":"encargadoprimero@almacen.es",
    "contrasena": "password123",
    "ciudad": "Barcelona",
    "codigo_postal":"08005",
    "roles_id":4,
    "usuarios_id_lider":26
}

###
//Recupera todos los usuarios
GET {{host}}/api/usuarios
authorization : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3Vhcmlvc19pZCI6MjYsInJvbGVzX2lkIjoyLCJleHAiOjE2ODk0NDE5OTQsImlhdCI6MTY4Njg0OTk5NH0.qVo6IEZNa8z6oPuiIU_P78wcDObQimiIxp9zZruEBcc

###
// para ver los detalles de un usuario
GET {{host}}/api/usuarios/31

###
// para actualizar los detalles de un usuario
PUT {{host}}/api/usuarios/25
Content-Type: application/json 

{
    "edad":26,
    "codigo_postul":"08006"
}


###
// para borrar un usuario
DELETE {{host}}/api/usuarios/29


